### ISSUE TITLE
project.json necessary?

### ISSUE THREAD

**Issue by daynewright** [nss-day-cohort-15/nss-day-cohort-15.github.io#11]
We currently have bower and NPM performing the same functionality.   Do we want to use Grunt or Gulp with this project to run jshint or SASS?  If not, then I don't think we need the project.json file.

**Comment by matthamil** [comment]
In all honestly, we should be able to use plain CSS and JS for a _static webpage_. 

¯\_(ツ)_/¯

**Comment by daynewright** [comment]
I guess you could leave off the bower components as well if we are just hosting with github pages and use a CDN?

**Comment by estorms** [comment]
Makes sense to me. Unless anyone indicates strong preferences by the end of this week, I'm game for CDN-only.
