### ISSUE TITLE
Wrong Repo?

### ISSUE THREAD

**Issue by garrett-vangilder** [nss-day-cohort-15/nss-day-cohort-15.github.io#15]
I thought this was the correct repo? 

https://github.com/nss-day-cohort-15/nss-day-cohort-15.github.io

**Comment by MattKraatz** [comment]
We can move stuff over there later if we want to host on github.

**Comment by matthamil** [comment]
Paging @sscotth. We don't have any permissions on https://github.com/nss-day-cohort-15/nss-day-cohort-15.github.io. Can we nuke the old repository and rename this one?

**Comment by matthamil** [comment]
@estorms Scott should have you set up on the other repository with permissions: https://github.com/nss-day-cohort-15/nss-day-cohort-15.github.io

**Comment by matthamil** [comment]
Resolved
