### ISSUE TITLE
Oops, you downloaded something and committed it to master

### ISSUE THREAD

**Issue by matthamil** [nss-day-cohort-15/nss-day-cohort-15.github.io#21]
There's a GitKraken installer `.dmg` file that somehow made its way into master.

Check the `img` folder: https://github.com/nss-day-cohort-15/class-website/tree/master/img/logo

**Comment by MattKraatz** [comment]
Oops... GitKraken is pretty cool btw 👀

**Comment by matthamil** [comment]
Lol, I also saw that email with the free year license from Nodevember 😜

**Comment by estorms** [comment]
Issue resolved. :)
