### ISSUE TITLE
Reintegrate bios into new design

### ISSUE THREAD

**Issue by estorms** [nss-day-cohort-15/nss-day-cohort-15.github.io#40]
### Feature Description
The current (kickass) design needs to include cohort members' bios, either on hover over prof. pic or elsewhere.

### Recommended Actions
Changes needed to scripts.js and/or index.html

### Related Issues/PRs
#23

**Comment by matthamil** [comment]
I'll hop on this tonight unless someone else claims it.

**Comment by estorms** [comment]
Beautifully resolved!
