### ISSUE TITLE
Do something fancy with the cards

### ISSUE THREAD

**Issue by MattKraatz** [nss-day-cohort-15/nss-day-cohort-15.github.io#8]
Add something fun to the `$(".memCard").hover(function(e) {` event handler in script.js to show employers that we know how to javascript.

**Comment by matthamil** [comment]
**NOTE:** The current styling (after #22) doesn't have a `memCard` class for each of the tiles in the DOM. Whoever claims this issue will have to make the appropriate changes to the `generateCards` function in `script.js`.

**Comment by matthamil** [comment]
Closing this issue, resolved with https://github.com/nss-day-cohort-15/nss-day-cohort-15.github.io/pull/41. If you're reading this and want to do more to the cards, feel free to reopen the issue!
